/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InitScreen {
    }
    interface InternalComponent {
    }
    interface InternalComponent2 {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RootComponent {
    }
}
declare global {
    interface HTMLInitScreenElement extends Components.InitScreen, HTMLStencilElement {
    }
    var HTMLInitScreenElement: {
        prototype: HTMLInitScreenElement;
        new (): HTMLInitScreenElement;
    };
    interface HTMLInternalComponentElement extends Components.InternalComponent, HTMLStencilElement {
    }
    var HTMLInternalComponentElement: {
        prototype: HTMLInternalComponentElement;
        new (): HTMLInternalComponentElement;
    };
    interface HTMLInternalComponent2Element extends Components.InternalComponent2, HTMLStencilElement {
    }
    var HTMLInternalComponent2Element: {
        prototype: HTMLInternalComponent2Element;
        new (): HTMLInternalComponent2Element;
    };
    interface HTMLRootComponentElement extends Components.RootComponent, HTMLStencilElement {
    }
    var HTMLRootComponentElement: {
        prototype: HTMLRootComponentElement;
        new (): HTMLRootComponentElement;
    };
    interface HTMLElementTagNameMap {
        "init-screen": HTMLInitScreenElement;
        "internal-component": HTMLInternalComponentElement;
        "internal-component2": HTMLInternalComponent2Element;
        "root-component": HTMLRootComponentElement;
    }
}
declare namespace LocalJSX {
    interface InitScreen {
    }
    interface InternalComponent {
    }
    interface InternalComponent2 {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RootComponent {
    }
    interface IntrinsicElements {
        "init-screen": InitScreen;
        "internal-component": InternalComponent;
        "internal-component2": InternalComponent2;
        "root-component": RootComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "init-screen": LocalJSX.InitScreen & JSXBase.HTMLAttributes<HTMLInitScreenElement>;
            "internal-component": LocalJSX.InternalComponent & JSXBase.HTMLAttributes<HTMLInternalComponentElement>;
            "internal-component2": LocalJSX.InternalComponent2 & JSXBase.HTMLAttributes<HTMLInternalComponent2Element>;
            "root-component": LocalJSX.RootComponent & JSXBase.HTMLAttributes<HTMLRootComponentElement>;
        }
    }
}
